contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #oceangenomesdraftgenomes channel"
    url: https://nfcore.slack.com/channels/oceangenomesdraftgenomes
    about: Discussion about the nf-core/oceangenomesdraftgenomes pipeline
